

-- ปิดการ Give Item
Config.disableGive = {
	-- อาวุธ -- 
 
	 WEAPON_BATLV1 	    = true,
	 oxygen_ambulance 	    = true,
	 WEAPON_GOLFLV1 	= true,
	 WEAPON_KNUCKLE 	= true,
	 WEAPON_FLASHLIGHT 	= true,
	 WEAPON_NIGHTSTICK 	= true,
	 WEAPON_HAMMER 		= true,
	 WEAPON_MACHETE 	= true,
	 WEAPON_BOTTLE 		= true,
	 WEAPON_STUNGUN 	= true,
	 WEAPON_SWITCHBLADE = true,
	 WEAPON_POOLCUE 	= true,
	 license_weapon		= true,
	 seller				= true,
	 bp_bat 	        = true,
	 bp_bottle 	        = true,
	 bp_golfclub 	        = true,
	 bp_machete 	        = true,
	 bp_knuckle 	        = true,
	 bp_knife 	        = true,
	 bp_poolcue 	        = true,
	 bp_battleaxe 	        = true,
	 Armourpolice = true,
	 foffmc = true,
	 PT_KNIFE = true,
	 PT_BAT = true,
	 PT_BOTTLE = true,
	 PT_BATTLEAXE = true,
	 PT_BATTLEAXELV = true,
	 PT_DAGGER = true,
	 PT_GOLFCLUB = true,
	 PT_KNUCKLE = true,
	 PT_KNUCKLELV = true,
	 PT_MACHETE = true,
	 PT_POOLCUE = true,
	 PT_REVOLVER = true,
 
	 
	 -- ไอเท็ม -- 
 
	 repair_agency = true,
	 basic_coin_cbt = true,
	 car_brioso = true,
	 r32_3day = true,
	 radio = true,
	 pain_agency = true,
	 new_player = true,
	 newplayer = true,
	 car_brioso = true,
	 gacha_newplayer = true,
	 card_key = true,
	 vault_key_am = true,
	 vault_key_pl = true,
	 x2_card = true,
	 tier1_box = true,
	 bp_golf_box = true,
	 bp_bottle_box = true,
	 bp_bat_box = true,

	 BP_BOTTLE = true,
	 BP_DAGGER = true,
	 BP_GOLF = true,
	 BP_KNIFEX = true,
	 BP_KNUCKLE = true,
	 BP_MACHETE = true,
	 BP_POOL = true,
	 G_BP_BAT = true,
	 G_BP_BOTTLE = true,
	 G_BP_DAGGER = true,
	 G_BP_GOLF = true,
	 G_BP_KNIFEX = true,
	 G_BP_KNUCKLE = true,
	 G_BP_MACHETE = true,
	 G_BP_POOL = true,

 
	 -- กุญเเจ --
 
	 key            = true,
 }
