Config.T = {}
Config.T['prograss_error'] = "เกิดข้อผิดพลาดลองใหม่อีกครั้ง"
Config.T['item_vaild_error'] = "ข้อมูลมีการเปลี่ยนแปลงกรุณาลองใหม่อีกครั้ง!"
Config.T['job_require_error'] = "คุณไม่ใช่หน่วยงานที่ระบบกำหนด"
Config.T['items_buy_require_error'] = "คุณไม่มีไอเทมที่ใช้ในการซื้อ"
Config.T['items_sell_require_error'] = "คุณไม่มีไอเทมที่ใช้ในการลงขาย"
Config.T['items_sell_bl_error'] = "ไอเทมนี้ไม่สามารถลงขายได้"
Config.T['player_inventory_isfull'] = "ช่องเก็บไอเทมของคุณเต็ม"
Config.T['player_account_error'] = "จำนวนเงินของคุณไม่เพียงพอ"
Config.T['sell_item_limit_error'] = "รายการไอเทมลงขายเต็ม!"
Config.T['player_vat_price_error'] = "เงินไม่พอจ่ายค่าภาษี"
Config.T['withdraw_player_account_error'] = "คุณไม่มียอดเงิน"
Config.T['buy_myitem_error'] = "ไม่สามารถซื้อไอเทมตัวเองได้"
Config.T['items_sell_only_error'] = "ไอเทมนี้ไม่สามารถลงขายได้"
Config.T['items_sell_cancel_error'] = "ไม่สามารถยกเลิกขายไอเทมได้"

Config.T['buy_success'] = "ซื้อไอเทมเรียบร้อยแล้ว"
Config.T['sell_success'] = "ลงขายไอเทมเรียบร้อยแล้ว"
Config.T['items_selling_cancel_success'] = "ยกเลิกขายไอเทมเรียบร้อยแล้ว"
Config.T['withdraw_success'] = "ถอนเงินเรียบร้อยแล้ว"
Config.T['items_selling_remove_success'] = "ทำการลบไอเทมเรียบร้อยแล้ว"

Config.T['bug'] = "อย่าทำบัคเลยหนุ่ม"