resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'
this_is_a_map "yes"
files {
	'water.xml',
}
data_file 'DLC_ITYP_REQUEST' 'stream/house_doorsx_fh_frontdoortwo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sx_housefuniture.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sx_garage_doorhouse2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sx_garage_doorhouse.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sx_garage_doorx2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/glass_house.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sx_outganghouse.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/wardrobe.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sx_picture.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/right_doorsx.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sx_light_house.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/right_doorsxtwo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/left__doorsxtwo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/int_medical.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/stairs_admin.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sx_adminstation.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sign_bosspcv1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/admin_door.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/wood_windowhouse.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/gangfloorhouse_sx001.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/floor_housetop.ytyp'